name: Build & Commit Artifacts

on:
  schedule:
    - cron: 0/30 * * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Checkout RSMod upstream
        uses: actions/checkout@v3
        with:
          repository: rsmod/rsmod
          path: upstream

      - name: Set up JDK 8 + Kotlin
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compute current CRC
        id: crc
        run: |
          ./gradlew computeSourceCrc --no-daemon
          CURRENT_CRC=$(cat build/source_crc.txt)
          echo "current_crc=$CURRENT_CRC" >> $GITHUB_OUTPUT
          if [ -f last_crc.txt ]; then
            PREV_CRC=$(cat last_crc.txt)
          else
            PREV_CRC=""
          fi
          if [ "$CURRENT_CRC" != "$PREV_CRC" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build & publish to local-maven
        if: steps.crc.outputs.changed == 'true'
        run: |
          ./gradlew publishExtraPublicationToLocalRepo --no-daemon

      - name: Bump version & commit artifacts
        if: steps.crc.outputs.changed == 'true'
        run: |
          # Determine current version from gradle.properties
          CURRENT_VER=$(grep '^version=' gradle.properties | cut -d'=' -f2 | tr -d ' "')
          echo "Current version: $CURRENT_VER"
          
          # Split into segments and increment the last (patch) digit
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VER"
          PATCH=$((PATCH + 1))
          NEW_VER="$MAJOR.$MINOR.$PATCH"
          echo "Bumping version to: $NEW_VER"

          # Update version in gradle.properties
          sed -i "s|^version=.*|version=$NEW_VER|" gradle.properties

         
          # Update CRC tracker
          echo "${{ steps.crc.outputs.current_crc }}" > last_crc.txt
          # Commit and push the changes
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradle.properties artifacts/ last_crc.txt
          git commit -m "Publish rsmod-extra v${CURRENT_VER} artifacts"
          git push